import { FaReact, FaNodeJs, FaDocker, FaGitAlt, FaAws } from "react-icons/fa";
import {
  SiNextdotjs,
  SiTailwindcss,
  SiThreedotjs,
  SiTypescript,
  SiJavascript,
  SiVuedotjs,
  SiMongodb,
  SiExpress,
  SiPostgresql,
  SiFirebase,
  SiRedux,
  SiGraphql,
  SiApollographql,
  SiSocketdotio,
  SiJsonwebtokens,
  SiGithub,
  SiVite,
  SiNestjs,
  SiSass,
  SiFigma,
  SiHtml5,
  SiCss3,
  SiWordpress,
  SiPhp,
  SiStripe,
  SiWebrtc,
  SiOpenai,
  SiMysql,
  SiStyledcomponents,
  SiPrisma,
  SiDjango,
  SiRedis,
  SiPython,
  SiReact,
  SiChartdotjs,
  SiMongoose,
} from "react-icons/si";
import { VscVscode } from "react-icons/vsc";

export type TechInfo = {
  name: string;
  icon: React.ComponentType;
  color: string;
};

export const technologies: { [key: string]: TechInfo } = {
  React: { name: "React", icon: FaReact, color: "#61DAFB" },
  "Next.js": { name: "Next.js", icon: SiNextdotjs, color: "#000000" },
  Tailwind: { name: "Tailwind", icon: SiTailwindcss, color: "#06B6D4" },
  "Three.js": { name: "Three.js", icon: SiThreedotjs, color: "#000000" },
  TypeScript: { name: "TypeScript", icon: SiTypescript, color: "#3178C6" },
  JavaScript: { name: "JavaScript", icon: SiJavascript, color: "#F7DF1E" },
  "Vue.js": { name: "Vue.js", icon: SiVuedotjs, color: "#4FC08D" },
  "Node.js": { name: "Node.js", icon: FaNodeJs, color: "#339933" },
  MongoDB: { name: "MongoDB", icon: SiMongodb, color: "#47A248" },
  Mongoose: { name: "Mongoose", icon: SiMongoose, color: "#880000" },
  Express: { name: "Express.js", icon: SiExpress, color: "#000000" },
  PostgreSQL: { name: "PostgreSQL", icon: SiPostgresql, color: "#336791" },
  Firebase: { name: "Firebase", icon: SiFirebase, color: "#FFCA28" },
  Redux: { name: "Redux", icon: SiRedux, color: "#764ABC" },
  GraphQL: { name: "GraphQL", icon: SiGraphql, color: "#E10098" },
  Apollo: { name: "Apollo", icon: SiApollographql, color: "#311C87" },
  SocketIO: { name: "Socket.IO", icon: SiSocketdotio, color: "#010101" },
  JWT: { name: "JWT", icon: SiJsonwebtokens, color: "#000000" },
  Docker: { name: "Docker", icon: FaDocker, color: "#0db7ed" },
  Git: { name: "Git", icon: FaGitAlt, color: "#F05032" },
  GitHub: { name: "GitHub", icon: SiGithub, color: "#181717" },
  VSCode: { name: "VS Code", icon: VscVscode, color: "#007ACC" },
  Vite: { name: "Vite", icon: SiVite, color: "#646CFF" },
  NestJS: { name: "NestJS", icon: SiNestjs, color: "#E0234E" },
  AWS: { name: "AWS", icon: FaAws, color: "#FF9900" },
  Sass: { name: "Sass", icon: SiSass, color: "#CD6799" },
  Figma: { name: "Figma", icon: SiFigma, color: "#F24E1E" },
  HTML: { name: "HTML", icon: SiHtml5, color: "#E34F26" },
  CSS: { name: "CSS", icon: SiCss3, color: "#1572B6" },
  WordPress: { name: "WordPress", icon: SiWordpress, color: "#21759B" },
  PHP: { name: "PHP", icon: SiPhp, color: "#777BB4" },
  Stripe: { name: "Stripe", icon: SiStripe, color: "#635BFF" },
  WebRTC: { name: "WebRTC", icon: SiWebrtc, color: "#333333" },
  OpenAI: { name: "OpenAI", icon: SiOpenai, color: "#412991" },
  "Weather API": { name: "Weather API", icon: SiJavascript, color: "#4299E1" },
  "Maps SDK": { name: "Maps SDK", icon: SiJavascript, color: "#34D399" },
  MySQL: { name: "MySQL", icon: SiMysql, color: "#00758F" },
  Redis: { name: "Redis", icon: SiRedis, color: "#DC382D" },
  Prisma: { name: "Prisma", icon: SiPrisma, color: "#0C344B" },
  "Styled Components": {
    name: "Styled Components",
    icon: SiStyledcomponents,
    color: "#DB7093",
  },
  Python: { name: "Python", icon: SiPython, color: "#3776AB" },
  Django: { name: "Django", icon: SiDjango, color: "#092E20" },
  "D3.js": { name: "D3.js", icon: SiJavascript, color: "#F7931E" },
  Celery: { name: "Celery", icon: SiPython, color: "#A3C940" },
  "CoinGecko API": {
    name: "CoinGecko API",
    icon: SiJavascript,
    color: "#FFD700",
  },
  "React Native": { name: "React Native", icon: SiReact, color: "#61DAFB" },
  "Chart.js": { name: "Chart.js", icon: SiChartdotjs, color: "#FF6384" },
};

export const techTagsList = Object.values(technologies);